# Generated by Django 5.0.6 on 2024-05-26 07:16

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_subject_remove_post_subject_alter_post_image_url_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='previousyearquestion',
            name='document',
        ),
        migrations.RemoveField(
            model_name='previousyearquestion',
            name='link',
        ),
        migrations.RemoveField(
            model_name='studymaterial',
            name='document',
        ),
        migrations.RemoveField(
            model_name='studymaterial',
            name='link',
        ),
        migrations.AddField(
            model_name='post',
            name='subject',
            field=models.CharField(default='No subject', max_length=200),
        ),
        migrations.AddField(
            model_name='previousyearquestion',
            name='file',
            field=models.FileField(default='default_file.pdf', upload_to='previous_year_questions/'),
        ),
        migrations.AddField(
            model_name='studymaterial',
            name='file',
            field=models.FileField(default=django.utils.timezone.now, upload_to='study_materials/'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='post',
            name='image_url',
            field=models.URLField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='previousyearquestion',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.subject'),
        ),
        migrations.AlterField(
            model_name='studymaterial',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.subject'),
        ),
        migrations.CreateModel(
            name='Forum',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('forum', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='blog.forum')),
            ],
        ),
    ]
