# Generated by Django 5.0.6 on 2024-05-26 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_previousyearquestion_link_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='studymaterial',
            name='link',
            field=models.URLField(blank=True),
        ),
    ]
